#!/usr/bin/env node
import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import {fileURLToPath} from "url";

async function main() {
  const DIRNAME = path.dirname(fileURLToPath(import.meta.url));
  const TOKENS_SRC = path.resolve(DIRNAME, "../src");
  const JS_OUT = path.resolve(DIRNAME, "../dist/js");

  fs.rmSync(JS_OUT, {recursive: true, force: true});
  fs.mkdirSync(JS_OUT, {recursive: true});

  const files = fs.readdirSync(TOKENS_SRC).filter(file => /\.ya?ml$/.test(file));

  if(!files.length) {
    console.error("⚠️ No YAML files found in", TOKENS_SRC);
    process.exit(1);
  }

  files.forEach((file) => {
    const name = path.basename(file, path.extname(file));
    const data = yaml.load(fs.readFileSync(path.join(TOKENS_SRC, file), "utf8"));

    const content = `// AUTOGENERATED FROM ../src/${file} - DO NOT EDIT\n\n`
      + `export default ${JSON.stringify(data, null, 2)};\n`;

    const outFile = path.join(JS_OUT, `${name}.js`);
    fs.writeFileSync(outFile, content);

    console.log(`✅ Generated ${path.relative(process.cwd(), outFile)}`);
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
