#!/usr/bin/env node
import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import {fileURLToPath} from "url";

async function main() {
  const DIRNAME = path.dirname(fileURLToPath(import.meta.url));
  const TOKENS_SRC = path.resolve(DIRNAME, "../src");
  const SCSS_OUT = path.resolve(DIRNAME, "../dist/scss");

  function toSassLiteral(value) {
    if(Array.isArray(value)) {
      return `(${value.map(_value => toSassLiteral(_value)).join(", ")})`;
    } else if(value !== null && typeof value === "object") {
      const entries = Object.entries(value).map(([key, value]) => {
        const safeKey = /^[a-zA-Z_-][\w-]*$/.test(key) ? key : `"${key}"`;
        return `${safeKey}: ${toSassLiteral(value)}`;
      });

      return `(${entries.join(", ")})`;
    } else {
      return `${value}`;
    }
  }

  fs.rmSync(SCSS_OUT, {recursive: true, force: true});
  fs.mkdirSync(SCSS_OUT, {recursive: true});

  const files = fs.readdirSync(TOKENS_SRC).filter(file => /\.ya?ml$/.test(file));

  if(!files.length) {
    console.error("⚠️ No YAML files found in", TOKENS_SRC);
    process.exit(1);
  }

  files.forEach((file) => {
    const name = path.basename(file, path.extname(file));
    const data = yaml.load(fs.readFileSync(path.join(TOKENS_SRC, file), "utf8"));

    let content = `// AUTOGENERATED FROM ../src/${file} - DO NOT EDIT\n\n`;

    Object.entries(data).forEach(([key, value]) => {
      content += `$${key}: ${toSassLiteral(value)} !default;\n\n`;
    });

    const outFile = path.join(SCSS_OUT, `_${name}.scss`);
    fs.writeFileSync(outFile, content);
    console.log(`✅ Generated ${path.relative(process.cwd(), outFile)}`);
  });
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
