#!/usr/bin/env node
/**
 * This file contains custom filters, formats, and transforms for Style
 * Dictionary (see ../sd.config.js and ../src/tokens).
 */

import StyleDictionary from "style-dictionary";
import config from "../sd.config.js";

/**
 * Animation tokens.
 *
 * Animation tokens need to be handled differently. Rather than using the
 * default CSS format, we'll use a custom format that outputs keyframes for the
 * animations themselves. For timing, we'll create custom formats for cubic
 * bezier curves and transition durations.
 */

// Custom filters for sd.config.js to use.
StyleDictionary.registerFilter({
  name: "excludeKeyframes",
  filter: token => token.$type !== "keyframes",
});

StyleDictionary.registerFilter({
  name: "includeKeyframes",
  filter: token => token.$type === "keyframes",
});

// Custom @keyframes format.
StyleDictionary.registerFormat({
  name: "css/keyframes/complex",
  format: ({dictionary}) => {
    return dictionary.allTokens
      .map((token) => {
        if (token.$type !== "keyframes") return "";

        // A frame is an object representing a ruleset within a keyframe set
        // (e.g. `0% {}`, `100% {}`, etc.)
        const frames = token.$value
          .map((frame) => {
            // WAAPI offsets use decimals, CSS uses percentages.
            const percent = `${frame.offset * 100}%`;

            const styles = Object.entries(frame)
              .filter(([key]) => key !== "offset")
              .map(([prop, value]) => {
                // WAAPI uses "easing", CSS uses "animation-timing-function"
                if (prop === "easing") {
                  return `    animation-timing-function: ${value};`;
                }

                return `    ${prop}: ${value};`;
              })
              .join("\n");

            return `  ${percent} {\n${styles}\n  }`;
          })
          .join("\n");

        // Construct `@keyframes` ruleset.
        return `@keyframes ${token.name} {\n${frames}\n}`;
      })
      .join("\n\n");
  },
});

/**
 * PHP objects.
 *
 * Custom format for storing token values as PHP objects accessible to Drupal
 * theme code.
 */

function toPhpArray(obj, indent = "    ") {
  if (typeof obj === "string") {
    return `'${obj.replace(/'/g, "\\'")}'`;
  }

  if (typeof obj === "number") {
    return obj;
  }

  if (Array.isArray(obj)) {
    const items = obj.map(item => `${indent}  ${toPhpArray(item, indent + "  ")}`);
    return `[\n${items.join(",\n")}\n${indent}]`;
  }

  if (typeof obj === "object" && obj !== null) {
    const entries = Object.entries(obj).map(([key, value]) => {
      return `${indent}  '${key}' => ${toPhpArray(value, indent + "  ")}`;
    });

    return `[\n${entries.join(",\n")}\n${indent}]`;
  }

  return "''";
}

StyleDictionary.registerFormat({
  name: "php/dynamic-tokens",
  format: ({dictionary}) => {
    const phpArrayString = toPhpArray(dictionary.allTokens);

    return `<?php

namespace Drupal\\tcds\\_gen\\ThemeTokens;

/**
 * Auto-generated by Style Dictionary. DO NOT EDIT.
 */
class ThemeTokens {
  /**
   * The complete resolved token tree.
   */
  private static array $tokens = ${phpArrayString};

  /**
   * Retrieves a specific token value or token group using dot notation.
   *
   * @param string $path e.g., 'color.theme.brand.primary' or 'size.breakpoint'
   * @return mixed The token value, a nested array of tokens, or null if not
   * found.
   */
  public static function get(string $path) {
    $keys = explode('.', $path);
    $current = self::$tokens;

    foreach ($keys as $key) {
      if (!is_array($current) || !array_key_exists($key, $current)) {
        return null;
      }

      $current = $current[$key];
    }

    return $current;
  }

  /**
   * Formats a token group into an associative array for Drupal Form API
   * #options.
   *
   * Looks for the '$value' key to identify token leaves.
   *
   * @param string $path e.g. 'space.layout'
   * @return array e.g. ["xs" => "Extra-small", "sm" => "Small"]
   */
  public static function getTokenList(string $path): array {
    $group = self::get($path);
    $options = [];

    if (is_array($group)) {
      foreach ($group as $key => $data) {
        // Check if it's a resolved token leave (has a $value property)
        if (is_array($data) && isset($data['$value'])) {
          $raw_value = is_array($data['$value'])
            ? implode(', ', $data['$value'])
            : (string) $data['$value'];

          if (isset($data['$description'])) {
            $options[$key] = $data['$description'];
          } else {
            $options[$key] = $key . ' (' . $raw_value . ')';
          }
        }
      }
    }

    return $options;
  }
}
`;
  },
})

// Custom transform for cubicBezier token types, converting native array value
// to CSS cubic-bezier() function.
StyleDictionary.registerTransform({
  type: "value",
  name: "value/cubic-bezier",
  filter: token => token.$type === "cubicBezier",
  transform: (token) => {
    if (!Array.isArray(token.$value)) return token.$value;
    return `cubic-bezier(${token.$value.join(", ")})`;
  },
});

// For JS token outputs, we just want the raw numerical value instead of the CSS
// unit.
// @todo In the future look into a more intelligent conversion to support other
// units like seconds. For now, as a rule, only use ms.
StyleDictionary.registerTransform({
  type: "value",
  name: "value/duration-js",
  filter: token => token.$type === "duration",
  transform: token => parseInt(token.$value), // "100ms" -> 100
});

/**
 * SVG tokens.
 *
 * Custom transform for turning SVG icons into embedded CSS URLs, for use as
 * custom property values.
 */

StyleDictionary.registerTransform({
  type: "value",
  name: "value/svg-url",
  filter: token => token.$type === "icon",
  transform: token => `url("data:image/svg+xml,${token.$value}")`,
});

const sd = new StyleDictionary(config);
await sd.buildAllPlatforms();

console.log("[Style Dictionary] Tokens built for all platforms.");
